dist: trusty
sudo: false

language: node_js

node_js:
  - "node"

branches:
  only:
    - master
    - /^\d.\d+-release$/

before_script:
  - npm install -g grunt-cli

script:
  - grunt build

notifications:
  email: false
  slack:
    rooms:
      - secure: "xTJfiKuAxMM6HIrR/SF/3AQA4tJsE8AcOoIYcKh3XtcDX4reAL+D3PqO3H6EnD05FPhV6jInVJ7SLJHRMiZt5uSFaXYcmc7fZ6xmmj5r8978uxfr4V7ZX2lgGlqlNtBJT0DzK2yeXGwbavohuNGe0BOuHkTtQI/6CtupHiPSIsV86Pynn1WhrFU9MmOIUDce67W1rsXEqPWqHbT2qy+gbo6pMYRKcBNDa+Vjv7dsoKK4HYzHFHnrXq0i2UwUmxEBPkU6pNEJS6tGcQDZO4t+rojy3qbQDy2VAVT03k1366znW/jNLoBG0FLJ5tTBOQsUiBccuM+f7yLBXJteDgUPxt7QNopD9zwlsKIgb+I55F0mb6z37/fV65XoaY5KSdrcLBF5TMQxfkEdRI0QChnx14+ueMpUS3gXbga3ZN0FLWlGKUBbb6v9PgmlJVLbDuaJNIy65XDdL4gTHEs7lD7X2519FD0Xns0bJfksTVYioJOttjbK3tR9EHW6AxSy9BQ30kL3JrAhdHXNjlA90QWNQGeiRC+nh0s/qLY3NWrTPJhFb+7XkwVW1/ggWE6DsFoNKNG40hTCkmNJCGPpUnjWsENc/xybYcwTHKLmHO9Bfp6fqazx1EPO677L30ydzs/5QtrJEysagpAyqjlLdcy55onaLgdzuDjQusYsi+B7AsE="
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
