dist: trusty
sudo: false

language: node_js

node_js:
  - "node"

branches:
  only:
    - master
    - /^\d.\d+-release$/

before_script:
  - npm install -g grunt-cli

script:
  - grunt build

notifications:
  email: false

git:
  depth: 30
