assets:
    packages:
        ngcore_vendor:
            base_path: '/bundles/netgencoreui/vendor'
            version: ~
            version_format: ~
        ngcore:
            base_path: '/bundles/netgencoreui'
            version: ~
            version_format: ~
